FROM bcs2s

WORKDIR /usr/bcs2s

RUN cd /usr/bcs2s/build/tests;							\
	echo "serverUrl=https://api.internal.braincloudservers.com/dispatcherv2" >ids.txt;\
	echo "appId=20001" >>ids.txt;\
	echo "secret=4e51b45c-030e-4f21-8457-dc53c9a0ed5f" >>ids.txt;\
	echo "version=1.0.0" >>ids.txt;\
	echo "childAppId=20005" >>ids.txt;\
	echo "childSecret=f8cec1cf-2f95-4989-910c-8caf598f83db" >>ids.txt;\
	echo "parentLevelName=Master" >>ids.txt;\
	echo "peerName=peerapp" >>ids.txt;\
	echo "serverName=TestServer" >>ids.txt;\
	echo "serverSecret=2ddf8355-c516-48dd-a6b0-e35bd75fac80" >>ids.txt;\
	echo "s2sUrl=https://api.internal.braincloudservers.com/s2sdispatcher" >>ids.txt;\
	./testbcs2s;